version: '3.7'
services:
  server:
    image: node:14
    user: node
    working_dir: /app
    ports:
      - 80:8080
      - 3003:3003
    volumes:
      - .:/app
    command: node main.js
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "10m"
